---
- name: Converge
  hosts: all
  tasks:
    - name: instalado GNU PG2
      apt:
        update_cache: yes
        name: gnupg2
        state: present
    - name: "Include iac_role_runtime"
      include_role:
        name: "iac_role_runtime"
